/*
 * Exercise 1.
 *
 * Fix the errors in the definition of List from § 13.2.5 and write out c++ 
 * code equivalent to what the compiler must generate for the definition of 
 * List and the function f( ). Run a small test case using your hand-generated 
 * code and the code generated by the compiler from the tem-plate version. If 
 * possible on your system given your knowledge, compare the generated code.
 *
 */
#include <iostream>

template<class T>
class list {
	struct link {
		link *pre;
		link *suc;
		T val;
		link(link *p, link *s, const T &v)
			: pre(p), suc(s), val(v) {}
	};

	link *head;

	public:
	list() : head(NULL) {}
	list(const T &t) : head(new link(NULL,NULL,t)) {}
	void print_all() const {
		for (link *p = head; p; p=p->suc)
			std::cout << p->val << std::endl;
	}
};

struct rec {
	operator int() {
		return 666;
	}
};

void f(const list<int> &li, const list<rec> &lr)
{
	li.print_all();
	lr.print_all();
}

int main() {}
